# Generated by Django 3.2.5 on 2021-07-21 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='isReleased',
            field=models.BooleanField(default=False),
        ),
    ]
